/**
 * @file src/features/market-flux/hooks/useMarketSimulation.js
 *
 * @description
 * Frontend-only simulation for Market Flux.
 *
 * - The market price random-walks continuously (every TICK_MS).
 * - The player picks Up or Down. The stake is deducted and a round starts.
 * - After ROUND_MS the price is compared with the round's opening price.
 * - A correct call climbs the multiplier ladder and pays stake x multiplier.
 *   Reaching the top step also pays the bonus and resets the ladder.
 *   A wrong call loses the stake and resets the ladder.
 * - After RESULT_MS the next round becomes available (30 rounds, then it loops).
 *
 * All tuning values are exported constants so payouts and pacing are easy to
 * adjust. The reducer is pure: randomness is generated by the tick timer and
 * passed in as `action.delta`.
 */

import { useCallback, useEffect, useReducer } from 'react'

import { DEFAULT_MARKET_ID, MARKETS, MARKETS_BY_ID } from '../data/markets'

export const MULTIPLIERS = [1, 2, 4, 6, 8, 10]
export const TOP_STEP = MULTIPLIERS.length - 1
export const TOTAL_ROUNDS = 30
export const BONUS_AMOUNT = 1000

export const MIN_STAKE = 5
export const MAX_STAKE = 500
export const STAKE_STEP = 5

export const ROUND_MS = 8000
const RESULT_MS = 1800
const TICK_MS = 4000 // one price update (and one slot-style reveal) per tick

const DEFAULT_MARKET = MARKETS_BY_ID[DEFAULT_MARKET_ID]
const START_BALANCE = 124.5
const START_STAKE = 10

const initialState = {
  marketId: DEFAULT_MARKET_ID,
  price: DEFAULT_MARKET.startPrice,
  startPrice: DEFAULT_MARKET.startPrice,
  direction: 'up',
  changePct: 0,
  balance: START_BALANCE,
  stake: START_STAKE,
  round: 1,
  step: 0,
  phase: 'idle', // 'idle' | 'live' | 'result'
  prediction: null, // 'up' | 'down'
  elapsed: 0,
  outcome: null, // { won, stake, payout, bonus }
}

/** Highest stake the player can currently afford (multiple of STAKE_STEP). */
function maxAffordableStake(balance) {
  const affordable = Math.floor(balance / STAKE_STEP) * STAKE_STEP
  return Math.max(MIN_STAKE, Math.min(MAX_STAKE, affordable))
}

function clampStake(stake, balance) {
  return Math.min(Math.max(stake, MIN_STAKE), maxAffordableStake(balance))
}

function reducer(state, action) {
  switch (action.type) {
    case 'TICK': {
      // action.unit is noise in [-1, 1]; the market sets how far it can move.
      const { volatility } = MARKETS_BY_ID[state.marketId]
      const price = state.price * (1 + action.unit * volatility)
      const direction = action.unit >= 0 ? 'up' : 'down'

      if (state.phase !== 'live') {
        return { ...state, price, direction }
      }

      const elapsed = state.elapsed + TICK_MS
      const changePct = (price / state.startPrice - 1) * 100

      if (elapsed < ROUND_MS) {
        return { ...state, price, direction, elapsed, changePct }
      }

      // Round complete: resolve the prediction.
      const won =
        state.prediction === 'up'
          ? price > state.startPrice
          : price < state.startPrice

      if (!won) {
        return {
          ...state,
          price,
          direction,
          elapsed,
          changePct,
          phase: 'result',
          step: 0,
          outcome: { won: false, stake: state.stake, payout: 0, bonus: 0 },
        }
      }

      const step = Math.min(state.step + 1, TOP_STEP)
      const payout = state.stake * MULTIPLIERS[step]
      const bonus = step === TOP_STEP ? BONUS_AMOUNT : 0

      return {
        ...state,
        price,
        direction,
        elapsed,
        changePct,
        phase: 'result',
        step,
        balance: state.balance + payout + bonus,
        outcome: { won: true, stake: state.stake, payout, bonus },
      }
    }

    case 'PREDICT': {
      if (state.phase !== 'idle' || state.balance < state.stake) return state
      return {
        ...state,
        phase: 'live',
        prediction: action.direction,
        balance: state.balance - state.stake,
        startPrice: state.price,
        elapsed: 0,
        changePct: 0,
        outcome: null,
      }
    }

    case 'NEXT_ROUND': {
      return {
        ...state,
        phase: 'idle',
        prediction: null,
        elapsed: 0,
        changePct: 0,
        outcome: null,
        round: state.round >= TOTAL_ROUNDS ? 1 : state.round + 1,
        // A completed ladder (bonus paid) starts over.
        step: state.outcome?.bonus ? 0 : state.step,
        stake: clampStake(state.stake, state.balance),
      }
    }

    case 'CHANGE_STAKE': {
      if (state.phase !== 'idle') return state
      return {
        ...state,
        stake: clampStake(state.stake + action.delta, state.balance),
      }
    }

    case 'SELECT_MARKET': {
      // Only between rounds, and only to a known market.
      const market = MARKETS_BY_ID[action.marketId]
      if (state.phase !== 'idle' || !market || market.id === state.marketId) {
        return state
      }
      return {
        ...state,
        marketId: market.id,
        price: market.startPrice,
        startPrice: market.startPrice,
        direction: 'up',
        changePct: 0,
      }
    }

    case 'RESET':
      return {
        ...initialState,
        marketId: state.marketId,
        price: state.price,
        startPrice: state.price,
      }

    default:
      return state
  }
}

/**
 * Market Flux simulation hook.
 *
 * @returns {object} Game state plus actions: predict, increaseStake,
 * decreaseStake, selectMarket, reset.
 */
export function useMarketSimulation() {
  const [state, dispatch] = useReducer(reducer, initialState)

  // Continuous market ticker.
  useEffect(() => {
    const id = setInterval(() => {
      dispatch({ type: 'TICK', unit: Math.random() * 2 - 1 })
    }, TICK_MS)
    return () => clearInterval(id)
  }, [])

  // Show the result briefly, then open the next round.
  useEffect(() => {
    if (state.phase !== 'result') return undefined
    const id = setTimeout(() => dispatch({ type: 'NEXT_ROUND' }), RESULT_MS)
    return () => clearTimeout(id)
  }, [state.phase])

  const predict = useCallback(
    (direction) => dispatch({ type: 'PREDICT', direction }),
    [],
  )
  const increaseStake = useCallback(
    () => dispatch({ type: 'CHANGE_STAKE', delta: STAKE_STEP }),
    [],
  )
  const decreaseStake = useCallback(
    () => dispatch({ type: 'CHANGE_STAKE', delta: -STAKE_STEP }),
    [],
  )
  const reset = useCallback(() => dispatch({ type: 'RESET' }), [])
  const selectMarket = useCallback(
    (marketId) => dispatch({ type: 'SELECT_MARKET', marketId }),
    [],
  )

  const isIdle = state.phase === 'idle'
  const isBroke = isIdle && state.balance < MIN_STAKE

  return {
    ...state,
    market: MARKETS_BY_ID[state.marketId],
    markets: MARKETS,
    canSelectMarket: isIdle,
    isBroke,
    canPredict: isIdle && !isBroke && state.balance >= state.stake,
    canDecrease: isIdle && state.stake > MIN_STAKE,
    canIncrease:
      isIdle && state.stake + STAKE_STEP <= maxAffordableStake(state.balance),
    predict,
    increaseStake,
    decreaseStake,
    reset,
    selectMarket,
  }
}