/**
 * @file src/features/market-flux/hooks/useMarketSimulation.js
 *
 * @description
 * Frontend-only simulation for Market Flux.
 *
 * - The market price random-walks continuously (every TICK_MS).
 * - The player picks Up or Down. The stake is deducted and a round starts.
 * - After ROUND_MS the price is compared with the round's opening price.
 * - The final price is then revealed by the odometer ('revealing' phase). The
 *   outcome is computed at once but only applied (balance, ladder, banner)
 *   when the reels have landed, so the result never spoils the reveal.
 * - A correct call climbs the multiplier ladder and pays stake x multiplier.
 *   Reaching the top step also pays the bonus and resets the ladder.
 *   A wrong call loses the stake and resets the ladder.
 * - After RESULT_MS the next round becomes available (30 rounds, then it loops).
 *
 * Near misses are labelled from the real result only. They never change the
 * outcome or the odds:
 *   'bonus' = lost while one step away from the bonus
 *   'photo' = lost by less than NEAR_MISS_PCT percent
 *
 * All tuning values are exported constants so payouts and pacing are easy to
 * adjust. The reducer is pure: randomness is generated by the tick timer and
 * passed in as `action.unit`.
 */

import { useCallback, useEffect, useReducer } from 'react'

import { DEFAULT_MARKET_ID, MARKETS, MARKETS_BY_ID } from '../data/markets'

export const MULTIPLIERS = [1, 2, 4, 6, 8, 10]
export const TOP_STEP = MULTIPLIERS.length - 1
export const TOTAL_ROUNDS = 30
export const BONUS_AMOUNT = 1000

export const MIN_STAKE = 5
export const MAX_STAKE = 500
export const STAKE_STEP = 5

export const ROUND_MS = 8000
const RESULT_MS = 1800
const TICK_MS = 4000 // one price update (and one slot-style reveal) per tick

// How long the odometer needs to land every reel (see MarketNumberSpinner),
// plus the extra time its near-miss tease adds. Keep REVEAL_MS above the
// longest normal reveal and NEAR_MISS_EXTRA_MS above the tease's extra time.
const REVEAL_MS = 3400
const NEAR_MISS_EXTRA_MS = 700

// Lost by less than this many percent of the opening price = 'photo' finish.
export const NEAR_MISS_PCT = 0.03

const DEFAULT_MARKET = MARKETS_BY_ID[DEFAULT_MARKET_ID]
const START_BALANCE = 124.5
const START_STAKE = 10

const initialState = {
  marketId: DEFAULT_MARKET_ID,
  price: DEFAULT_MARKET.startPrice,
  startPrice: DEFAULT_MARKET.startPrice,
  direction: 'up',
  changePct: 0,
  balance: START_BALANCE,
  stake: START_STAKE,
  round: 1,
  step: 0,
  phase: 'idle', // 'idle' | 'live' | 'revealing' | 'result'
  prediction: null, // 'up' | 'down'
  elapsed: 0,
  outcome: null, // { won, stake, payout, bonus, nearMiss, marginPct }
  pending: null, // { step, balance, outcome } held back while 'revealing'
}

/** Highest stake the player can currently afford (multiple of STAKE_STEP). */
function maxAffordableStake(balance) {
  const affordable = Math.floor(balance / STAKE_STEP) * STAKE_STEP
  return Math.max(MIN_STAKE, Math.min(MAX_STAKE, affordable))
}

function clampStake(stake, balance) {
  return Math.min(Math.max(stake, MIN_STAKE), maxAffordableStake(balance))
}

/**
 * Works out what a finished round means, without applying it yet.
 *
 * @param {object} state Current state.
 * @param {boolean} won Whether the prediction was right.
 * @param {number} changePct Price change over the round, in percent.
 * @returns {{step: number, balance: number, outcome: object}}
 */
function settleRound(state, won, changePct) {
  if (!won) {
    const marginPct = Math.abs(changePct)
    let nearMiss = null
    if (state.step === TOP_STEP - 1) nearMiss = 'bonus'
    else if (marginPct < NEAR_MISS_PCT) nearMiss = 'photo'

    return {
      step: 0,
      balance: state.balance,
      outcome: {
        won: false,
        stake: state.stake,
        payout: 0,
        bonus: 0,
        nearMiss,
        marginPct,
      },
    }
  }

  const step = Math.min(state.step + 1, TOP_STEP)
  const payout = state.stake * MULTIPLIERS[step]
  const bonus = step === TOP_STEP ? BONUS_AMOUNT : 0

  return {
    step,
    balance: state.balance + payout + bonus,
    outcome: {
      won: true,
      stake: state.stake,
      payout,
      bonus,
      nearMiss: null,
      marginPct: Math.abs(changePct),
    },
  }
}

function reducer(state, action) {
  switch (action.type) {
    case 'TICK': {
      // action.unit is noise in [-1, 1]; the market sets how far it can move.
      const { volatility } = MARKETS_BY_ID[state.marketId]
      const price = state.price * (1 + action.unit * volatility)
      const direction = action.unit >= 0 ? 'up' : 'down'

      // The price holds still while the reels land and the result is shown.
      if (state.phase === 'revealing' || state.phase === 'result') return state

      if (state.phase !== 'live') {
        return { ...state, price, direction }
      }

      const elapsed = state.elapsed + TICK_MS
      const changePct = (price / state.startPrice - 1) * 100

      if (elapsed < ROUND_MS) {
        return { ...state, price, direction, elapsed, changePct }
      }

      // Round complete: work out the result, but hold it back until the
      // odometer has finished revealing the final price.
      const won =
        state.prediction === 'up'
          ? price > state.startPrice
          : price < state.startPrice

      return {
        ...state,
        price,
        direction,
        elapsed,
        changePct,
        phase: 'revealing',
        pending: settleRound(state, won, changePct),
      }
    }

    case 'REVEAL_DONE': {
      if (state.phase !== 'revealing' || !state.pending) return state
      return {
        ...state,
        phase: 'result',
        step: state.pending.step,
        balance: state.pending.balance,
        outcome: state.pending.outcome,
        pending: null,
      }
    }

    case 'PREDICT': {
      if (state.phase !== 'idle' || state.balance < state.stake) return state
      return {
        ...state,
        phase: 'live',
        prediction: action.direction,
        balance: state.balance - state.stake,
        startPrice: state.price,
        elapsed: 0,
        changePct: 0,
        outcome: null,
      }
    }

    case 'NEXT_ROUND': {
      return {
        ...state,
        phase: 'idle',
        prediction: null,
        elapsed: 0,
        changePct: 0,
        outcome: null,
        round: state.round >= TOTAL_ROUNDS ? 1 : state.round + 1,
        // A completed ladder (bonus paid) starts over.
        step: state.outcome?.bonus ? 0 : state.step,
        stake: clampStake(state.stake, state.balance),
      }
    }

    case 'CHANGE_STAKE': {
      if (state.phase !== 'idle') return state
      return {
        ...state,
        stake: clampStake(state.stake + action.delta, state.balance),
      }
    }

    case 'SELECT_MARKET': {
      // Only between rounds, and only to a known market.
      const market = MARKETS_BY_ID[action.marketId]
      if (state.phase !== 'idle' || !market || market.id === state.marketId) {
        return state
      }
      return {
        ...state,
        marketId: market.id,
        price: market.startPrice,
        startPrice: market.startPrice,
        direction: 'up',
        changePct: 0,
      }
    }

    case 'RESET':
      return {
        ...initialState,
        marketId: state.marketId,
        price: state.price,
        startPrice: state.price,
      }

    default:
      return state
  }
}

/**
 * Market Flux simulation hook.
 *
 * @returns {object} Game state plus actions: predict, increaseStake,
 * decreaseStake, selectMarket, reset.
 */
export function useMarketSimulation() {
  const [state, dispatch] = useReducer(reducer, initialState)

  // Continuous market ticker. It restarts when a round begins or the round
  // number changes, so a round always gets full TICK_MS steps (the first tick
  // is never a few milliseconds after the player picks).
  const isLive = state.phase === 'live'
  useEffect(() => {
    const id = setInterval(() => {
      dispatch({ type: 'TICK', unit: Math.random() * 2 - 1 })
    }, TICK_MS)
    return () => clearInterval(id)
  }, [isLive, state.round])

  // When the reels have landed, apply the result. A near miss takes a little
  // longer, because the last reel teases.
  const nearMiss = state.pending?.outcome.nearMiss ?? null
  useEffect(() => {
    if (state.phase !== 'revealing') return undefined
    const wait = REVEAL_MS + (nearMiss ? NEAR_MISS_EXTRA_MS : 0)
    const id = setTimeout(() => dispatch({ type: 'REVEAL_DONE' }), wait)
    return () => clearTimeout(id)
  }, [state.phase, nearMiss])

  // Show the result briefly, then open the next round.
  useEffect(() => {
    if (state.phase !== 'result') return undefined
    const id = setTimeout(() => dispatch({ type: 'NEXT_ROUND' }), RESULT_MS)
    return () => clearTimeout(id)
  }, [state.phase])

  const predict = useCallback(
    (direction) => dispatch({ type: 'PREDICT', direction }),
    [],
  )
  const increaseStake = useCallback(
    () => dispatch({ type: 'CHANGE_STAKE', delta: STAKE_STEP }),
    [],
  )
  const decreaseStake = useCallback(
    () => dispatch({ type: 'CHANGE_STAKE', delta: -STAKE_STEP }),
    [],
  )
  const reset = useCallback(() => dispatch({ type: 'RESET' }), [])
  const selectMarket = useCallback(
    (marketId) => dispatch({ type: 'SELECT_MARKET', marketId }),
    [],
  )

  const isIdle = state.phase === 'idle'
  const isBroke = isIdle && state.balance < MIN_STAKE

  return {
    ...state,
    market: MARKETS_BY_ID[state.marketId],
    markets: MARKETS,
    canSelectMarket: isIdle,
    teasing: state.phase === 'revealing' && nearMiss !== null,
    isBroke,
    canPredict: isIdle && !isBroke && state.balance >= state.stake,
    canDecrease: isIdle && state.stake > MIN_STAKE,
    canIncrease:
      isIdle && state.stake + STAKE_STEP <= maxAffordableStake(state.balance),
    predict,
    increaseStake,
    decreaseStake,
    reset,
    selectMarket,
  }
}